version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vollmed_web
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_web
      MYSQL_USER: root
      MYSQL_PASSWORD: root
